// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const CreateProjectOptions: CLICommandOption[] = [
  {
    name: "project-type",
    type: "string",
    description: "New Project",
    required: true,
    choices: ["copilot-agent-type", "bot-type"],
  },
  {
    name: "capabilities",
    type: "string",
    description: "App Features Using Agents",
    choices: ["api-plugin", "declarative-agent"],
  },
  {
    name: "with-plugin",
    type: "string",
    description: "Create Declarative Agent",
    default: "no",
    choices: ["no", "yes"],
  },
  {
    name: "api-plugin-type",
    type: "string",
    description: "Create API Plugin",
    default: "new-api",
    choices: ["new-api", "api-spec"],
  },
  {
    name: "api-auth",
    type: "string",
    description: "Authentication Type",
    default: "none",
    choices: ["none", "api-key", "oauth"],
  },
  {
    name: "openapi-spec-location",
    type: "string",
    shortName: "a",
    description: "OpenAPI description document location.",
  },
  {
    name: "api-operation",
    type: "array",
    description: "Select Operation(s) Teams Can Interact with",
  },
  {
    name: "bot-host-type-trigger",
    type: "string",
    description: "Select triggers",
    choices: ["http-express", "http-and-timer-functions", "http-functions", "timer-functions"],
  },
  {
    name: "programming-language",
    type: "string",
    description: "Programming Language",
    choices: ["javascript", "typescript", "csharp", "python"],
  },
  {
    name: "folder",
    type: "string",
    description: "Workspace Folder",
    required: true,
    default: "C:\\Users\\nintan\\TeamsApps",
  },
  {
    name: "app-name",
    type: "string",
    description: "Application Name",
    required: true,
  },
];
export const CreateProjectArguments: CLICommandArgument[] = [];
