// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const CreateSampleProjectOptions: CLICommandOption[] = [
  {
    name: "folder",
    type: "string",
    shortName: "f",
    description: "Directory where the project folder will be created in.",
    required: true,
    default: "./",
  },
];
export const CreateSampleProjectArguments: CLICommandArgument[] = [
  {
    name: "sample-name",
    questionName: "samples",
    type: "string",
    description: "Specifies the Teams App sample name.",
    required: true,
    choiceListCommand: "teamsfx list samples",
    skipValidation: true,
  },
];
