// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const SPFxAddWebpartOptions: CLICommandOption[] = [
  {
    name: "spfx-folder",
    type: "string",
    description: "Directory or Path that contains the existing SharePoint Framework solution.",
    required: true,
  },
  {
    name: "spfx-webpart-name",
    type: "string",
    shortName: "w",
    description: "Name for SharePoint Framework Web Part.",
    required: true,
    default: "helloworld",
  },
  {
    name: "spfx-framework-type",
    type: "string",
    shortName: "k",
    description: "Framework.",
    required: true,
    default: "react",
    choices: ["react", "minimal", "none"],
  },
  {
    name: "teams-manifest-file",
    questionName: "manifest-path",
    type: "string",
    shortName: "t",
    description:
      "Specify the path for Teams app manifest template. It can be either absolute path or relative path to the project root folder, with default at './appPackage/manifest.json'",
    required: true,
    default: "./appPackage/manifest.json",
  },
  {
    name: "local-teams-manifest-file",
    questionName: "local-manifest-path",
    type: "string",
    shortName: "l",
    description:
      "Specifies the Microsoft Teams app manifest template file path for local environment, it can be either absolute path or relative path to project root folder.",
    required: true,
    default: "./appPackage/manifest.local.json",
  },
];
export const SPFxAddWebpartArguments: CLICommandArgument[] = [];
