// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const UninstallOptions: CLICommandOption[] = [
  {
    name: "title-id",
    type: "string",
    description: "Remove the acquired M365 App by Title ID",
    required: true,
  },
  {
    name: "manifest-id",
    type: "string",
    description: "Remove the acquired M365 App by Manifest ID",
    required: true,
  },
  {
    name: "env",
    type: "string",
    description: "Remove the acquired M365 App by local env",
    required: true,
  },
];
export const UninstallArguments: CLICommandArgument[] = [];
