// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const UninstallOptions: CLICommandOption[] = [
  {
    name: "uninstall-mode",
    type: "string",
    description: "Choose Uninstall Mode",
    required: true,
    default: "uninstall-env",
    choices: ["uninstall-manifest-id", "uninstall-env", "uninstall-title-id"],
  },
  {
    name: "manifest-id",
    type: "string",
    description: "Manifest ID",
  },
  {
    name: "env",
    type: "string",
    description: "Env",
  },
  {
    name: "projectPath",
    type: "string",
    description: "Project Path for uninstall",
    default: "./",
  },
  {
    name: "titile-id",
    type: "string",
    description: "Title ID",
  },
];
export const UninstallArguments: CLICommandArgument[] = [];
