name: Create Sprint Milestone
description: Create Sprint Milestone
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    required: true
  devops-org:
    description: 'the org to create work item'
    required: true
  devops-projectId:
    description: 'the project to create work item'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
