// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// NOTE:
// DO NOT EDIT this file in function plugin.
// The source of truth of this file is in packages/vscode-extension/src/debug/depsChecker.
// If you need to edit this file, please edit it in the above folder
// and run the scripts (tools/depsChecker/copyfiles.sh or tools/depsChecker/copyfiles.ps1 according to your OS)
// to copy you changes to function plugin.

import { defaultHelpLink, dotnetNotSupportTargetVersionHelpLink } from "./common";
import { DotnetChecker } from "./dotnetChecker";
import { BackendExtensionsInstallError } from "./errors";
import { cpUtils } from "./cpUtils";
import { IDepsLogger } from "./checker";

// NOTE: change these constants if function plugin scaffold changes
const defaultOutputPath = "bin";
const defaultCsprojPath = "extensions.csproj";

export class BackendExtensionsInstaller {
  private readonly _dotnetChecker: DotnetChecker;
  private readonly _logger: IDepsLogger;

  constructor(dotnetChecker: DotnetChecker, logger: IDepsLogger) {
    this._dotnetChecker = dotnetChecker;
    this._logger = logger;
  }

  public async install(backendRoot: string, csprojPath: string = defaultCsprojPath, outputPath: string = defaultOutputPath): Promise<void> {
    if (!outputPath) {
      outputPath = defaultOutputPath;
    }

    const dotnetExecPath = await this._dotnetChecker.getDotnetExecPath();

    if (dotnetExecPath === "") {
      await this._logger.printDetailLog();
      this._logger.cleanup();
      await this._logger.error(`Failed to run backend extension install, .NET SDK executable not found`);
      throw new BackendExtensionsInstallError("Failed to run backend extension install, .NET SDK executable not found", defaultHelpLink);
    }

    try {
      const result: cpUtils.ICommandResult = await cpUtils.tryExecuteCommand(
          backendRoot,
          this._logger,
          { shell: false },
          dotnetExecPath,
          "build",
          csprojPath,
          "-o",
          outputPath,
          "--ignore-failed-sources"
      );
      if (result.code !== 0) {
        throw new Error(`Failed to run "${dotnetExecPath} build" command. output = ${result.cmdOutput}, err = ${result.cmdOutputIncludingStderr}`);
      }
    } catch (error) {
      await this._logger.printDetailLog();
      await this._logger.error(`Failed to run backend extension install: error = '${error}'`);

      if(error.message.includes("NETSDK1045")) {
        // refer to https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1045
        throw new BackendExtensionsInstallError(`NETSDK1045: The current .NET SDK does not support 'newer version' as a target`, dotnetNotSupportTargetVersionHelpLink);
      }
      throw new BackendExtensionsInstallError(`Failed to run backend extension install: error = '${error}'`, defaultHelpLink);
    } finally {
      this._logger.cleanup();
    }
  }
}
