@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.JSInterop
@using {{SafeProjectName}}
@using {{SafeProjectName}}.Shared
@using {{SafeProjectName}}.Interop.TeamsSDK;
@using {{SafeProjectName}}.Components
@using Microsoft.Fast.Components.FluentUI;
@using Microsoft.TeamsFx
