// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file list feature flag settings that should be handled during release. For example, if we want to have a feature being enabled only on alpha and beta version.
// Please do not edit this file except introducing new feature flag settings.
// During cd, we will modify the value of the feature flag settings in this file.
// Please list each setting line by line. The default value should be the expected value in stable release, which is false usually.
const shouldEnableTeamsCopilotChatUI = false;

export const releaseControlledFeatureSettings = {
  shouldEnableTeamsCopilotChatUI,
};
