// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export enum AppCategory {
  Analytics,
  Communication,
  ContentManagement,
  CustomerAndContactManagement,
  CustomerSupport,
  DataVisualizationAndBI,
  DeveloperTools,
  Education,
  FilesAndDocuments,
  FinancialManagement,
  HumanResourcesAndRecruiting,
  ImageAndVideoGalleries,
  ITAdmin,
  Jobs,
  LabApp,
  Lifestyle,
  LookAndFeel,
  MapsAndFeeds,
  MeetingsAndScheduling,
  Microsoft,
  NewsAndWeather,
  Other,
  PrintingAndFaxing,
  Productivity,
  ProjectManagement,
  PublicFacingWebsites,
  Reference,
  SalesAndMarketing,
  SearchAndDiscoverability,
  SecurityAndCompliance,
  Social,
  TrainingAndTutorial,
  TravelAndNavigation,
  Utilities,
  WorkflowAndBusinessManagement,
}
