// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { Result } from "neverthrow";
import {
  EnvMeta,
  FunctionRouter,
  FxError,
  QTreeNode,
  TokenProvider,
  Void,
  Func,
  Json,
} from "../index";
import { AppStudioTokenProvider, AzureAccountProvider } from "../utils";
import { Context, Inputs, Stage } from "./types";

export type ResourceTemplate = BicepTemplate | JsonTemplate;

export type JsonTemplate = {
  kind: "json";
  template: Json;
};

export type BicepTemplate = {
  kind: "bicep";
  // The format of template can be found at https://microsoftapc.sharepoint.com/:w:/t/DevDivTeamsDevXProductTeam/EZCuSzABypNBr30K-_wvRVEBksF1-ftqVv8l-34art1FFw?e=nEYfZK
  template: Record<string, unknown>;
};

export interface ResourceProvisionContext extends Context {
  envMeta: EnvMeta;

  solutionConfig: Json;
  resourceConfig: Json;
}

export type ResourceDeployContext = ResourceProvisionContext;

export type ProvisionOutput = {
  output: Record<string, string>;
  states: Record<string, string>;
  // Encryption and decryption are transparantly handled by the toolkit.
  secrets: Record<string, string>;
};

export type LocalProvisionOutput = ProvisionOutput;

/**
 * Interface for ResourcePlugins. a ResourcePlugin can hook into Toolkit's
 * lifecycles by implementing the corresponding API.
 * All lifecycles follows the same pattern of returning a Promise<Result<T, FxError>>.
 *
 * Please prefer to return {@link UserError} or {@link SystemError} when error happens
 * instead of throwing.
 *
 */
export interface ResourcePlugin {
  // Name used by the toolkit to uniquely identify this plugin.
  name: string;

  // Plugin name that will be shown to end users.
  displayName: string;

  /**
   * Called by Toolkit when creating a new project or adding a new resource.
   * Scaffolds source code on disk, relative to context.projectPath
   *
   * @example
   * ```
   * const fs = require("fs-extra");
   * let content = "let x = 1;"
   * let path = path.join(ctx.projectPath, "myFolder");
   * let sourcePath = "somePathhere";
   * let result = await fs.copy(sourcePath, content);
   * ```
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Inputs} inputs - User answers to quesions defined in {@link getQuestionsForLifecycleTask}
   * for {@link Stage.create} along with some system inputs.
   *
   * @returns Void because side effect is expected.
   */
  scaffoldSourceCode?: (ctx: Context, inputs: Inputs) => Promise<Result<Void, FxError>>;

  /**
   * Called when creating a new project or a new environment.
   * Returns resource templates (e.g. Bicep templates/plain JSON) for provisioning.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Inputs} inputs - User's answers to quesions defined in {@link getQuestionsForLifecycleTask}
   * for {@link Stage.createEnv} along with some system inputs.
   *
   * @return {@link ResourceTemplate} for provisioning and deployment.
   */
  generateResourceTemplate?: (
    ctx: Context,
    inputs: Inputs
  ) => Promise<Result<ResourceTemplate, FxError>>;

  /**
   * This method is useful for resources that can't be provisioned using Bicep/ARM like AAD, AppStudio.
   * Plugins are expected to provision using Azure SDK.
   *
   * provisionResource is guaranteed to run before Bicep provision.
   * Implementation of provisionResource is expected to be idempotent.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Json} provisionTemplate - provision template
   * @param {TokenProvider} tokenProvider - Tokens for Azure and AppStudio
   *
   * @returns the config, project state, secrect values for the current environment. Toolkit will persist them
   *          and pass them to {@link configureResource}.
   */
  provisionResource?: (
    ctx: Context,
    provisionTemplate: Json,
    tokenProvider: TokenProvider
  ) => Promise<Result<ProvisionOutput, FxError>>;

  /**
   * configureResource is guaranteed to run after Bicep/ARM provisioning.
   * Plugins are expected to read the provision output values of other plugins, and return a new copy of its own provisionOutput,
   * possibly with added fields.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Json} provisionOutput - values generated by {@link provisionResource}
   * @param {Record<string, Json>} provisionOutputOfOtherPlugins - values of other plugins generated by {@link provisionResource}
   * @param {TokenProvider} tokenProvider - Tokens for Azure and AppStudio
   *
   * @returns a new copy of provisionOutput possibly with added fields. Toolkit will persist it and pass it to {@link deploy}.
   *
   */
  configureResource?: (
    ctx: Context,
    provisionOutput: Readonly<ProvisionOutput>,
    provisionOutputOfOtherPlugins: Readonly<Record<string, ProvisionOutput>>,
    tokenProvider: TokenProvider
  ) => Promise<Result<ProvisionOutput, FxError>>;

  /**
   * Generates a Teams manifest package for the current project,
   * and stores it on disk.
   *
   * On failure, plugins are responsible for cleaning up.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Inputs} inputs - User answers to quesions defined in {@link getQuestionsForLifecycleTask}
   * for {@link Stage.package} along with some system inputs.
   *
   * @returns Void because side effect is expected.
   */
  package?: (ctx: Context, inputs: Inputs) => Promise<Result<Void, FxError>>;

  /**
   * Depends on the values returned by {@link provisionResource} and {@link configureResource}.
   * Plugins are expected to deploy Code to cloud using credentials provided by {@link TokenProvider}.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Json} provisionTemplate - output generated during provision
   * @param {TokenProvider} tokenProvider - Tokens for Azure and AppStudio
   *
   * @returns Void because side effects are expected.
   */
  deploy?: (
    ctx: Context,
    provisionOutput: ProvisionOutput,
    tokenProvider: AzureAccountProvider
  ) => Promise<Result<Void, FxError>>;

  /**
   * Depends on the output of {@link package}. Uploads Teams package to AppStudio
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {AppStudioTokenProvider} tokenProvider - Token for AppStudio
   * @param {Inputs} inputs - User answers to quesions defined in {@link getQuestionsForLifecycleTask}
   * for {@link Stage.publish} along with some system inputs.
   *
   * @returns Void because side effect is expected.
   */
  publishApplication?: (
    ctx: Context,
    tokenProvider: AppStudioTokenProvider,
    inputs: Inputs
  ) => Promise<Result<Void, FxError>>;

  /**
   * provisionLocalResource is a special stage, called when users hit F5 in vscode.
   * It works like provision, but only creates necessary cloud resources for local debugging like AAD and AppStudio App.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {TokenProvider} tokenProvider - Tokens for Azure and AppStudio
   *
   * @returns the config, project state, secrect values for the current environment. Toolkit will persist them
   *          and pass them to {@link configureLocalResource}.
   */
  provisionLocalResource?: (
    ctx: Context,
    tokenProvider: TokenProvider
  ) => Promise<Result<LocalProvisionOutput, FxError>>;

  /**
   * configureLocalResource works like {@link configureResource} but only for local debugging resources.
   * Plugins are expected to read the local provision output values of other plugins, and return a new copy of its own local provision output,
   * possibly with added fields.
   *
   * @param {Context} ctx - plugin's runtime context shared by all lifecycles.
   * @param {Json} localProvisionOutput - values generated by {@link provisionLocalResource}
   * @param {Record<string, LocalProvisionOutput>} provisionOutputOfOtherPlugins - values of other plugins generated by {@link provisionLocalResource}
   * @param {TokenProvider} tokenProvider - Tokens for Azure and AppStudio
   *
   * @returns a new copy of provisionOutput possibly with added fields. Toolkit will persist it and pass it to {@link deploy}.
   *
   */
  configureLocalResource?: (
    ctx: Context,
    localProvisionOutput: LocalProvisionOutput,
    localProvisionOutputOfOtherPlugins: Readonly<Record<string, LocalProvisionOutput>>,
    tokenProvider: TokenProvider
  ) => Promise<Result<LocalProvisionOutput, FxError>>;

  getQuestionsForLifecycleTask?: (
    ctx: Context,
    stage: Stage,
    inputs: Inputs
  ) => Promise<Result<QTreeNode | undefined, FxError>>;

  getQuestionsForUserTask?: (
    ctx: Context,
    router: FunctionRouter,
    inputs: Inputs
  ) => Promise<Result<QTreeNode | undefined, FxError>>;

  // Building teams package is now defined as a user task
  executeUserTask?: (ctx: Context, func: Func, inputs: Inputs) => Promise<Result<unknown, FxError>>;
}
