// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Microsoft.TeamsFx.Helper;
using System;

namespace Microsoft.TeamsFx
{
    public enum ExceptionCode
    {
        /// <summary>
        /// Invalid parameter error.
        /// </summary>
        InvalidParameter,
        /// <summary>
        /// Invalid configuration error.
        /// </summary>
        InvalidConfiguration,
        /// <summary>
        /// Internal error.
        /// </summary>
        InternalError,
        /// <summary>
        /// Channel is not supported error.
        /// </summary>
        ChannelNotSupported,
        /// <summary>
        /// Runtime is not supported error.
        /// </summary>
        RuntimeNotSupported,
        /// <summary>
        /// User failed to finish the AAD consent flow failed.
        /// </summary>
        ConsentFailed,
        /// <summary>
        /// The user or administrator has not consented to use the application error.
        /// </summary>
        UiRequiredError,
        /// <summary>
        /// Token is not within its valid time range error.
        /// </summary>
        TokenExpiredError,
        /// <summary>
        /// Call service (AAD or simple authentication server) failed.
        /// </summary>
        ServiceError,
        /// <summary>
        /// Operation failed.
        /// </summary>
        FailedOperation,
        /// <summary>
        /// General JSException that are not generated by TeamsFx SDK. 
        /// </summary>
        JSRuntimeError,
    }

    public class ExceptionWithCode : Exception
    {
        public readonly ExceptionCode Code;
        internal ExceptionWithCode(Exception e) : base(e.Message)
        {
            Code = ExceptionHelper.ParseExceptionCode(e);
        }

        internal ExceptionWithCode(string message, ExceptionCode exceptionCode) : base(message)
        {
            Code = exceptionCode;
        }
    }
}
