// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface AddPluginInputs extends Inputs {
  /** @description Add API plugin */
  "api-plugin-type"?: "api-spec" | "existing-plugin";
  /** @description Import manifest file */
  "plugin-manifest-path"?: string;
  /** @description Import OpenAPI description document */
  "plugin-opeanapi-spec-path"?: string;
  /** @description OpenAPI Description Document */
  "openapi-spec-location"?: string;
  /** @description Select Operation(s) Copilot Can Interact with */
  "api-operation"?: string[];
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
}
