// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface AddPluginInputs extends Inputs {
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
  /** @description Select Plugin Availability */
  "plugin-availability"?: "api-plugin" | "action" | "api-plugin-and-action";
  /** @description OpenAPI Description Document */
  "openapi-spec-location"?: string;
  /** @description Select Operation(s) Copilot Can Interact with */
  "api-operation"?: string[];
}
