// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface DeclarativeAgentBotInputs extends Inputs {
  /** @description Should the bot being created support multi tenant? */
  "multi-tenant"?: string;
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
}
