// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface PermissionGrantInputs extends Inputs {
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
  /** @description Select an environment */
  env?: string;
  /** @description Select Microsoft Entra manifest.json file */
  "manifest-file-path"?: string;
  /** @description Add owner to Teams/Microsoft Entra app for the account under the same Microsoft 365 tenant (email) */
  email?: string;
}
