// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface PermissionListInputs extends Inputs {
  /** @description Select Teams manifest.json file */
  "manifest-path"?: string;
  /** @description Select an environment */
  env?: string;
  /** @description Select Azure Active Directory manifest.json file */
  "manifest-file-path"?: string;
}
