// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface SyncManifestInputs extends Inputs {
  /** @description Project path */
  projectPath?: string;
  /** @description Target Teams Toolkit Environment */
  env?: string;
  /** @description Teams App ID (optional) */
  "teams-app-id"?: string;
}
