// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface UninstallInputs extends Inputs {
  /** @description Choose Uninstall Mode */
  "uninstall-mode"?: "uninstall-manifest-id" | "uninstall-env" | "uninstall-title-id";
  /** @description Manifest ID */
  "manifest-id"?: string;
  /** @description Env */
  env?: string;
  /** @description Project path */
  projectPath?: string;
  /** @description Title ID */
  "titile-id"?: string;
}
