// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface UninstallInputs extends Inputs {
  /** @description Remove the acquired M365 App by Title ID */
  "title-id"?: string;
  /** @description Remove the acquired M365 App by Manifest ID */
  "manifest-id"?: string;
  /** @description Remove the acquired M365 App by local env */
  env?: string;
}
