// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface ValidateTeamsAppInputs extends Inputs {
  /** @description Select Teams manifest.json file */
  "manifest-path"?: string;
  /** @description Select Teams app package file */
  "app-package-file-path"?: string;
}
