output frontendHosting_storageName string = frontendHostingProvision.outputs.storageName
output frontendHosting_endpoint string = frontendHostingProvision.outputs.endpoint
output frontendHosting_domain string = frontendHostingProvision.outputs.domain
