// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
"use strict";

import {
  Inputs,
  LocalSettings,
  PluginConfig,
  ProjectSettings,
  ReadonlySolutionConfig,
  SolutionConfig,
} from "./types";

import {
  GraphTokenProvider,
  LogProvider,
  TelemetryReporter,
  AzureAccountProvider,
  AppStudioTokenProvider,
  TreeProvider,
} from "./utils";
import { UserInteraction } from "./qm";
import { CryptoProvider } from "./utils";

/*
 * Context will be generated by Core and carry necessary information to
 * develop a Teams APP.
 */
export interface Context {
  root: string;

  targetEnvName?: string;

  logProvider?: LogProvider;

  telemetryReporter?: TelemetryReporter;

  azureAccountProvider?: AzureAccountProvider;

  graphTokenProvider?: GraphTokenProvider;

  appStudioToken?: AppStudioTokenProvider;

  treeProvider?: TreeProvider;

  answers?: Inputs;

  projectSettings?: ProjectSettings;

  localSettings?: LocalSettings;

  ui?: UserInteraction;

  cryptoProvider?: CryptoProvider;
}

export interface SolutionContext extends Context {
  // dotVsCode?: VsCode;

  // app: TeamsAppManifest;

  config: SolutionConfig;
}

export interface PluginContext extends Context {
  // A readonly view of other plugins' config
  configOfOtherPlugins: ReadonlySolutionConfig;

  // A mutable config for current plugin
  config: PluginConfig;
}
