name: setup project
description: setup project by default installing dependencies and running setup script
inputs:
  setup:  # id of input
    description: 'setup project'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    
    - name: Setup project
      if: ${{ inputs.setup == 'true' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: |
          npm run setup