{
  "component": {
    "version": 1,
    "id": "browserM365SignIn",
    "answerType": "authentication",
    "parameters": ["instanceSuffix", "accountName", "accountPassword"]
  },
  "steps": [
    {
      "step_id": "step_browserM365SignIn_assertAccount_{{text:instanceSuffix}}",
      "agent": "assertion",
      "tool": "",
      "parameters": {},
      "description": "@assertion the Microsoft sign-in page is visible in Chrome with an email or username input.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": [],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser", "step_retry_timeout: 180"]
    },
    {
      "step_id": "step_browserM365SignIn_focusAccount_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "click",
      "parameters": { "button": "left", "x": 429, "y": 347 },
      "description": "Click the email or username input on the Microsoft sign-in page.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_assertAccount_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser"]
    },
    {
      "step_id": "step_browserM365SignIn_enterAccount_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "type_text",
      "parameters": { "text": {{json:accountName}} },
      "description": "Enter the registered Microsoft 365 account in the browser sign-in form.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_focusAccount_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser"]
    },
    {
      "step_id": "step_browserM365SignIn_submitAccount_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "key_press",
      "parameters": { "key": "enter" },
      "description": "Press Enter to continue to password entry.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_enterAccount_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser"]
    },
    {
      "step_id": "step_browserM365SignIn_assertPassword_{{text:instanceSuffix}}",
      "agent": "assertion",
      "tool": "",
      "parameters": {},
      "description": "@assertion the Microsoft sign-in password input is visible and focused in Chrome.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_submitAccount_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser", "step_retry_timeout: 120"]
    },
    {
      "step_id": "step_browserM365SignIn_enterPassword_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "type_text",
      "parameters": { "text": {{json:accountPassword}} },
      "description": "Enter the registered Microsoft 365 password in the browser sign-in form.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_assertPassword_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser"]
    },
    {
      "step_id": "step_browserM365SignIn_submitPassword_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "key_press",
      "parameters": { "key": "enter" },
      "description": "Press Enter to submit the Microsoft 365 password.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_enterPassword_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser"]
    },
    {
      "step_id": "step_browserM365SignIn_assertStaySignedIn_{{text:instanceSuffix}}",
      "agent": "assertion",
      "tool": "",
      "parameters": {},
      "description": "@assertion the Microsoft Stay signed in question is visible with Yes focused.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_submitPassword_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser", "step_retry_timeout: 120"]
    },
    {
      "step_id": "step_browserM365SignIn_confirmStaySignedIn_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "key_press",
      "parameters": { "key": "enter" },
      "description": "Press Enter to confirm staying signed in.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_assertStaySignedIn_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser", "delay: 30"]
    },
    {
      "step_id": "step_browserM365SignIn_zoomOut_{{text:instanceSuffix}}",
      "agent": "interaction",
      "tool": "keyboard_shortcut",
      "parameters": { "keys": "ctrl+-" },
      "description": "Zoom the browser out once with Ctrl+- so the Microsoft 365 Copilot navigation rail stops covering the conversation column.",
      "content_refs": [],
      "timeout": 30,
      "retry_count": 0,
      "continue_on_error": "false",
      "depends_on": ["step_browserM365SignIn_confirmStaySignedIn_{{text:instanceSuffix}}"],
      "preconditions": [],
      "postconditions": [],
      "tags": ["component:authentication", "surface:browser"]
    }
  ]
}
