name: DotNet Api Scan
schedules:
- cron: "0 7 * * *"
  displayName: Daily run
  branches:
    include:
    - dev

pool: "$(POOLAGENT)"

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6.0'
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
     packages/function-extension
     packages/dotnet-sdk
    arguments: '/p:Configuration=Release'

# Remove files that won't be released
- task: APIScan@2
  displayName: 'Run APIScan'
  inputs:
    softwareFolder: 'packages/function-extension/src/bin/Release/netcoreapp3.1'
    softwareName: TeamsFxFunctionExtension
    softwareVersionNum: '$(Build.BuildId)'
    isLargeApp: false
    verbosityLevel: 'none'
  env:
    AzureServicesAuthConnectionString: 'RunAs=App;AppId=$(ApiScanClientId)'

- task: APIScan@2
  displayName: 'Run APIScan on Microsoft.TeamsFx'
  inputs:
    softwareFolder: packages/dotnet-sdk/src/TeamsFx/bin/Release/net6.0
    softwareName: TeamsFx
    softwareVersionNum: '$(Build.BuildId)'
    isLargeApp: false
    verbosityLevel: 'none'
  env:
    AzureServicesAuthConnectionString: 'RunAs=App;AppId=$(ApiScanClientId)'
