name: duplicate issue check for app-studio-service 
on:
  issues:
    types: [opened]
  workflow_dispatch: # allows to run manually for testing
    inputs:
      issueNumber:
        description: 'specific issue number to test duplicate issue check for app-studio-service action'
        required: true  

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github action repository
        uses: actions/checkout@v3
        with:
         repository: "microsoft/vscode-github-triage-actions"
         ref: stable 
         path: ./action-base

      - name: Copy action
        run: |
          cp -r .github/actions/duplicate-handler-for-app-studio ./action-base/duplicate-handler-for-app-studio
          cp -r .github/actions/teamsfx-utils ./action-base/teamsfx-utils

      - name: Npm install
        run: npm install --production --prefix ./action-base
      - name: Build action
        continue-on-error: true
        run: npm run build --prefix ./action-base

      - name: Check duplicate
        uses: ./action-base/duplicate-handler-for-app-studio
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
          reply: Based on the status code and API name in error message, this issue is duplicated with {{first}}. You can refer to it for more information.
          adding-tags: close-wait,*duplicate
        env:
          ISSUE_NUMBER: ${{github.event.inputs.issueNumber}}
          