name: rerun failed jobs

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "run id"
        required: true
        type: string
      max_attempts:
        description: "max attempts, default is 3"
        required: false
        default: "3"
        type: string

permissions:
  actions: read

jobs:
  rerun:
    permissions:
      actions: write
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      DEVTUNNEL_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
      DEVTUNNEL_CLIENT_SECRET: ${{ secrets.TEST_CLEAN_CLIENT_SECRET }}
      DEVTUNNEL_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}
    steps:
      - name: wait for 60s
        run: |
          echo "wait for 60s"

  clean:
    name: Clean resource
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tests
    env:
      M365_ACCOUNT_NAME: "test14@xxbdw.onmicrosoft.com"
      M365_ACCOUNT_PASSWORD: ${{ secrets.TEST_M365_PASSWORD }}
      M365_DISPLAY_NAME: "ttktest"
      M365_USERNAME_2: "test15@xxbdw.onmicrosoft.com"
      M365_USERNAME_3: "test16@xxbdw.onmicrosoft.com"
      M365_USERNAME_4: "test17@xxbdw.onmicrosoft.com"
      CLEAN_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
      CLEAN_CLIENT_SECRET: ${{ secrets.CLEAN_CLIENT_SECRET }}
      CLEAN_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}
      AZURE_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID }}
      AZURE_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
      AZURE_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      MAIL_API_KEY: ${{ secrets.MAIL_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4

      - name: Setup project
        working-directory: ./
        run: |
          npm run setup

      - name: Clean resource
        if: always()
        run: |
          npx ts-node src/scripts/clean.ts
