name: Duplicate Handler for App Studio Service Issue
description: Duplicate Handler for App Studio Service Issue
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    required: true
  reply:
    description: 'the reply will be added in the issue. Using {{first}} to refer to the first issue.'
    required: true
  adding-tags:
    description: 'the tags will be added for the issue, seperated by comma'

runs:
  using: 'node16'
  main: 'index.js'
